//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;



/// <summary>
///   一个强类型的资源类，用于查找本地化的字符串等。
/// </summary>
// 此类是由 StronglyTypedResourceBuilder
// 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
// 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
// (以 /str 作为命令选项)，或重新生成 VS 项目。
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public class MtProviderConfDialogResources {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal MtProviderConfDialogResources() {
    }
    
    /// <summary>
    ///   返回此类使用的缓存的 ResourceManager 实例。
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MtProviderConfDialogResources", typeof(MtProviderConfDialogResources).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   使用此强类型资源类，为所有资源查找
    ///   重写当前线程的 CurrentUICulture 属性。
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   查找类似 &amp;Cancel 的本地化字符串。
    /// </summary>
    public static string btn_Cancel_Text {
        get {
            return ResourceManager.GetString("btn_Cancel_Text", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 &amp;OK 的本地化字符串。
    /// </summary>
    public static string btn_OK_Text {
        get {
            return ResourceManager.GetString("btn_OK_Text", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Browse... 的本地化字符串。
    /// </summary>
    public static string btnBrowsePostEditFile_Text {
        get {
            return ResourceManager.GetString("btnBrowsePostEditFile_Text", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Browse... 的本地化字符串。
    /// </summary>
    public static string btnBrowsePreEdit_Text {
        get {
            return ResourceManager.GetString("btnBrowsePreEdit_Text", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Delete Baidu APPID and Key 的本地化字符串。
    /// </summary>
    public static string btnDeleteSavedBaiduCreds_Text {
        get {
            return ResourceManager.GetString("btnDeleteSavedBaiduCreds_Text", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Delete saved key 的本地化字符串。
    /// </summary>
    public static string btnDeleteSavedGoogleKey_Text {
        get {
            return ResourceManager.GetString("btnDeleteSavedGoogleKey_Text", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Delete saved credentials 的本地化字符串。
    /// </summary>
    public static string btnDeleteSavedMicrosoftCreds_Text {
        get {
            return ResourceManager.GetString("btnDeleteSavedMicrosoftCreds_Text", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Use category ID: 的本地化字符串。
    /// </summary>
    public static string chkCatId_Text {
        get {
            return ResourceManager.GetString("chkCatId_Text", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Send plain text only (no tags) 的本地化字符串。
    /// </summary>
    public static string chkPlainTextOnly_Text {
        get {
            return ResourceManager.GetString("chkPlainTextOnly_Text", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Re-send draft and translated segments 的本地化字符串。
    /// </summary>
    public static string chkResendDrafts_Text {
        get {
            return ResourceManager.GetString("chkResendDrafts_Text", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Save ID and Key for future sessions 的本地化字符串。
    /// </summary>
    public static string chkSaveAppIDandKey_Text {
        get {
            return ResourceManager.GetString("chkSaveAppIDandKey_Text", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Save credentials for future sessions 的本地化字符串。
    /// </summary>
    public static string chkSaveCred_Text {
        get {
            return ResourceManager.GetString("chkSaveCred_Text", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Save key for future sessions 的本地化字符串。
    /// </summary>
    public static string chkSaveKey_Text {
        get {
            return ResourceManager.GetString("chkSaveKey_Text", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Do post-lookup find/replace 的本地化字符串。
    /// </summary>
    public static string chkUsePostEdit_Text {
        get {
            return ResourceManager.GetString("chkUsePostEdit_Text", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Do pre-lookup find/replace 的本地化字符串。
    /// </summary>
    public static string chkUsePreEdit_Text {
        get {
            return ResourceManager.GetString("chkUsePreEdit_Text", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 The saved credentials were deleted 的本地化字符串。
    /// </summary>
    public static string deleteCredentialsMessageSavedCredsDeleted {
        get {
            return ResourceManager.GetString("deleteCredentialsMessageSavedCredsDeleted", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 There are no credentials currently saved 的本地化字符串。
    /// </summary>
    public static string deleteCredentialsMessageSavedCredsEmpty {
        get {
            return ResourceManager.GetString("deleteCredentialsMessageSavedCredsEmpty", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 The saved key was deleted 的本地化字符串。
    /// </summary>
    public static string deleteCredentialsMessageSavedKeyDeleted {
        get {
            return ResourceManager.GetString("deleteCredentialsMessageSavedKeyDeleted", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 There is no key currently saved 的本地化字符串。
    /// </summary>
    public static string deleteCredentialsMessageSavedKeyEmpty {
        get {
            return ResourceManager.GetString("deleteCredentialsMessageSavedKeyEmpty", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
    /// </summary>
    public static System.Drawing.Icon form_Icon {
        get {
            object obj = ResourceManager.GetObject("form_Icon", resourceCulture);
            return ((System.Drawing.Icon)(obj));
        }
    }
    
    /// <summary>
    ///   查找类似 Settings 的本地化字符串。
    /// </summary>
    public static string form_Text {
        get {
            return ResourceManager.GetString("form_Text", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Choose MT provider 的本地化字符串。
    /// </summary>
    public static string groupBox3_Text {
        get {
            return ResourceManager.GetString("groupBox3_Text", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 MT provider 的本地化字符串。
    /// </summary>
    public static string groupBox3_Text_creds_only {
        get {
            return ResourceManager.GetString("groupBox3_Text_creds_only", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Provider Options 的本地化字符串。
    /// </summary>
    public static string groupBox4_Text {
        get {
            return ResourceManager.GetString("groupBox4_Text", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Baidu Credentials 的本地化字符串。
    /// </summary>
    public static string groupBoxBT_Text {
        get {
            return ResourceManager.GetString("groupBoxBT_Text", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Google Translate API key 的本地化字符串。
    /// </summary>
    public static string groupBoxGT_Text {
        get {
            return ResourceManager.GetString("groupBoxGT_Text", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Microsoft Translator credentials 的本地化字符串。
    /// </summary>
    public static string groupBoxMT_Text {
        get {
            return ResourceManager.GetString("groupBoxMT_Text", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Post-lookup find/replace filename: 的本地化字符串。
    /// </summary>
    public static string groupBoxPostedit_Text {
        get {
            return ResourceManager.GetString("groupBoxPostedit_Text", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Pre-lookup find/replace filename: 的本地化字符串。
    /// </summary>
    public static string groupBoxPreedit_Text {
        get {
            return ResourceManager.GetString("groupBoxPreedit_Text", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 NOTE: once key has been saved, it can be deleted by pressing the delete button, 的本地化字符串。
    /// </summary>
    public static string KeyForm_SaveKeyTooltip1 {
        get {
            return ResourceManager.GetString("KeyForm_SaveKeyTooltip1", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 NOTE: once key has been saved, it can be deleted by pressing the delete button, 的本地化字符串。
    /// </summary>
    public static string KeyForm_SaveKeyTooltip1_BD {
        get {
            return ResourceManager.GetString("KeyForm_SaveKeyTooltip1_BD", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 NOTE: once credentials have been saved, they can be deleted by pressing the delete button, 的本地化字符串。
    /// </summary>
    public static string KeyForm_SaveKeyTooltip1_MS {
        get {
            return ResourceManager.GetString("KeyForm_SaveKeyTooltip1_MS", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 or by leaving box unchecked and clicking &apos;Ok&apos;. 的本地化字符串。
    /// </summary>
    public static string KeyForm_SaveKeyTooltip2 {
        get {
            return ResourceManager.GetString("KeyForm_SaveKeyTooltip2", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Simply removing the provider will not delete the key after it has been saved. 的本地化字符串。
    /// </summary>
    public static string KeyForm_SaveKeyTooltip3 {
        get {
            return ResourceManager.GetString("KeyForm_SaveKeyTooltip3", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Simply removing the provider will not delete the credentials after they have been saved. 的本地化字符串。
    /// </summary>
    public static string KeyForm_SaveKeyTooltip3_BD {
        get {
            return ResourceManager.GetString("KeyForm_SaveKeyTooltip3_BD", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Simply removing the provider will not delete the credentials after they have been saved. 的本地化字符串。
    /// </summary>
    public static string KeyForm_SaveKeyTooltip3_MS {
        get {
            return ResourceManager.GetString("KeyForm_SaveKeyTooltip3_MS", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Baidu APP ID 的本地化字符串。
    /// </summary>
    public static string lbAppID_Text {
        get {
            return ResourceManager.GetString("lbAppID_Text", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Baidu API Key 的本地化字符串。
    /// </summary>
    public static string lbBaiduApiKey_Text {
        get {
            return ResourceManager.GetString("lbBaiduApiKey_Text", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Client ID: 的本地化字符串。
    /// </summary>
    public static string lblClientID_Text {
        get {
            return ResourceManager.GetString("lblClientID_Text", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Client Secret: 的本地化字符串。
    /// </summary>
    public static string lblClientSecret_Text {
        get {
            return ResourceManager.GetString("lblClientSecret_Text", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Choose post-lookup edit file 的本地化字符串。
    /// </summary>
    public static string lookupFileDialogPostLookupCaption {
        get {
            return ResourceManager.GetString("lookupFileDialogPostLookupCaption", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Choose pre-lookup edit file 的本地化字符串。
    /// </summary>
    public static string lookupFileDialogPreLookupCaption {
        get {
            return ResourceManager.GetString("lookupFileDialogPreLookupCaption", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 File error 的本地化字符串。
    /// </summary>
    public static string lookupFileStructureCheckErrorCaption {
        get {
            return ResourceManager.GetString("lookupFileStructureCheckErrorCaption", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 There was a problem with the selected file: 的本地化字符串。
    /// </summary>
    public static string lookupFileStructureCheckGenericErrorMessage {
        get {
            return ResourceManager.GetString("lookupFileStructureCheckGenericErrorMessage", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 There was a problem loading the file: &apos;{0}&apos;. Make sure the contents are properly-formatted XML according to the required specifications, which are described in the plugin&apos;s documentation. 的本地化字符串。
    /// </summary>
    public static string lookupFileStructureCheckXmlProblemErrorMessage {
        get {
            return ResourceManager.GetString("lookupFileStructureCheckXmlProblemErrorMessage", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Choose provider 的本地化字符串。
    /// </summary>
    public static string tabPage1_Text {
        get {
            return ResourceManager.GetString("tabPage1_Text", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Set credentials 的本地化字符串。
    /// </summary>
    public static string tabPage1_Text_creds_only {
        get {
            return ResourceManager.GetString("tabPage1_Text_creds_only", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Provider options 的本地化字符串。
    /// </summary>
    public static string tabPage3_Text {
        get {
            return ResourceManager.GetString("tabPage3_Text", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Please correct the following problem(s): 的本地化字符串。
    /// </summary>
    public static string validationMessageHeader {
        get {
            return ResourceManager.GetString("validationMessageHeader", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Google Translate selected but API key not specified 的本地化字符串。
    /// </summary>
    public static string validationMessageNoApiKey {
        get {
            return ResourceManager.GetString("validationMessageNoApiKey", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Baidu Translate selected but APP ID not specified 的本地化字符串。
    /// </summary>
    public static string validationMessageNoAPPID {
        get {
            return ResourceManager.GetString("validationMessageNoAPPID", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Baidu Translate selected but API Key not specified 的本地化字符串。
    /// </summary>
    public static string validationMessageNoBaiduApiKey {
        get {
            return ResourceManager.GetString("validationMessageNoBaiduApiKey", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Category ID option checked but no category ID specified 的本地化字符串。
    /// </summary>
    public static string validationMessageNoCatId {
        get {
            return ResourceManager.GetString("validationMessageNoCatId", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Microsoft Translator selected but Client ID not specified 的本地化字符串。
    /// </summary>
    public static string validationMessageNoClientId {
        get {
            return ResourceManager.GetString("validationMessageNoClientId", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Microsoft Translator selected but Client Secret not specified 的本地化字符串。
    /// </summary>
    public static string validationMessageNoClientSecret {
        get {
            return ResourceManager.GetString("validationMessageNoClientSecret", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Post-lookup find/replace option checked but no post-lookup find/replace file specified 的本地化字符串。
    /// </summary>
    public static string validationMessageNoPostLookupFile {
        get {
            return ResourceManager.GetString("validationMessageNoPostLookupFile", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Pre-lookup find/replace option checked but no pre-lookup find/replace file specified 的本地化字符串。
    /// </summary>
    public static string validationMessageNoPreLookupFile {
        get {
            return ResourceManager.GetString("validationMessageNoPreLookupFile", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 No provider specified 的本地化字符串。
    /// </summary>
    public static string validationMessageNoProvider {
        get {
            return ResourceManager.GetString("validationMessageNoProvider", resourceCulture);
        }
    }
}
