//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;



/// <summary>
///   一个强类型的资源类，用于查找本地化的字符串等。
/// </summary>
// 此类是由 StronglyTypedResourceBuilder
// 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
// 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
// (以 /str 作为命令选项)，或重新生成 VS 项目。
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class PluginResources {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal PluginResources() {
    }
    
    /// <summary>
    ///   返回此类使用的缓存的 ResourceManager 实例。
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PluginResources", typeof(PluginResources).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   使用此强类型资源类，为所有资源查找
    ///   重写当前线程的 CurrentUICulture 属性。
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   查找类似 No API key has been set.  Please open the plugin settings form and enter a valid API key 的本地化字符串。
    /// </summary>
    internal static string ApiConnectionGoogleNoKeyErrorMessage {
        get {
            return ResourceManager.GetString("ApiConnectionGoogleNoKeyErrorMessage", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 There was a problem getting the translation. 的本地化字符串。
    /// </summary>
    internal static string ApiConnectorGoogleAuthErrorMsg1 {
        get {
            return ResourceManager.GetString("ApiConnectorGoogleAuthErrorMsg1", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Please verify that you have entered the correct API key and that your language pair is supported. 的本地化字符串。
    /// </summary>
    internal static string ApiConnectorGoogleAuthErrorMsg2 {
        get {
            return ResourceManager.GetString("ApiConnectorGoogleAuthErrorMsg2", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 MT Enhanced using Baidu Translate 的本地化字符串。
    /// </summary>
    internal static string Baidu_Description {
        get {
            return ResourceManager.GetString("Baidu_Description", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找 System.Drawing.Bitmap 类型的本地化资源。
    /// </summary>
    internal static System.Drawing.Bitmap baidu_image {
        get {
            object obj = ResourceManager.GetObject("baidu_image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   查找类似 MT Enhanced using Baidu Translate 的本地化字符串。
    /// </summary>
    internal static string Baidu_Name {
        get {
            return ResourceManager.GetString("Baidu_Name", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 MT Enhanced using Baidu Translate 的本地化字符串。
    /// </summary>
    internal static string Baidu_NiceName {
        get {
            return ResourceManager.GetString("Baidu_NiceName", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 MT Enhanced using Baidu Translate 的本地化字符串。
    /// </summary>
    internal static string Baidu_Tooltip {
        get {
            return ResourceManager.GetString("Baidu_Tooltip", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Baidu API Errors 的本地化字符串。
    /// </summary>
    internal static string BtApiErrorMessage {
        get {
            return ResourceManager.GetString("BtApiErrorMessage", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Amount not enough to use Baidu API 的本地化字符串。
    /// </summary>
    internal static string BtApiOutOfMoneyErrorMessage {
        get {
            return ResourceManager.GetString("BtApiOutOfMoneyErrorMessage", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Edit settings error 的本地化字符串。
    /// </summary>
    internal static string EditSettingsErrorCaption {
        get {
            return ResourceManager.GetString("EditSettingsErrorCaption", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Error with edit settings: 的本地化字符串。
    /// </summary>
    internal static string EditSettingsGenericErrorMessage {
        get {
            return ResourceManager.GetString("EditSettingsGenericErrorMessage", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 There was a problem with the file: &apos;{0}&apos;. Make sure the contents are properly-formatted XML according to the required specifications, which are described in the plugin&apos;s documentation. 的本地化字符串。
    /// </summary>
    internal static string EditSettingsXmlErrorMessage {
        get {
            return ResourceManager.GetString("EditSettingsXmlErrorMessage", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 MT Enhanced using Google Translate 的本地化字符串。
    /// </summary>
    internal static string Google_Description {
        get {
            return ResourceManager.GetString("Google_Description", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 MT Enhanced using Google Translate 的本地化字符串。
    /// </summary>
    internal static string Google_Name {
        get {
            return ResourceManager.GetString("Google_Name", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 MT Enhanced using Google Translate 的本地化字符串。
    /// </summary>
    internal static string Google_NiceName {
        get {
            return ResourceManager.GetString("Google_NiceName", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 MT Enhanced using Google Translate 的本地化字符串。
    /// </summary>
    internal static string Google_Tooltip {
        get {
            return ResourceManager.GetString("Google_Tooltip", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 There was a problem checking language pair support. 的本地化字符串。
    /// </summary>
    internal static string LangPairAuthErrorMsg1 {
        get {
            return ResourceManager.GetString("LangPairAuthErrorMsg1", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Please verify that you have entered the correct API key. 的本地化字符串。
    /// </summary>
    internal static string LangPairAuthErrorMsg2 {
        get {
            return ResourceManager.GetString("LangPairAuthErrorMsg2", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 If the problem persists, close/reopen the current dialog and try again 的本地化字符串。
    /// </summary>
    internal static string LangPairAuthErrorMsg3 {
        get {
            return ResourceManager.GetString("LangPairAuthErrorMsg3", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 MT Enhanced using Microsoft Translator 的本地化字符串。
    /// </summary>
    internal static string Microsoft_Description {
        get {
            return ResourceManager.GetString("Microsoft_Description", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找 System.Drawing.Bitmap 类型的本地化资源。
    /// </summary>
    internal static System.Drawing.Bitmap microsoft_image {
        get {
            object obj = ResourceManager.GetObject("microsoft_image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   查找类似 MT Enhanced using Microsoft Translator 的本地化字符串。
    /// </summary>
    internal static string Microsoft_Name {
        get {
            return ResourceManager.GetString("Microsoft_Name", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 MT Enhanced using Microsoft Translator 的本地化字符串。
    /// </summary>
    internal static string Microsoft_NiceName {
        get {
            return ResourceManager.GetString("Microsoft_NiceName", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 MT Enhanced using Microsoft Translator 的本地化字符串。
    /// </summary>
    internal static string Microsoft_Tooltip {
        get {
            return ResourceManager.GetString("Microsoft_Tooltip", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Authentication error: bad credentials 的本地化字符串。
    /// </summary>
    internal static string MsApiBadCredentialsMessage {
        get {
            return ResourceManager.GetString("MsApiBadCredentialsMessage", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Invalid category ID. Use a valid category ID or disable category ID in settings. 的本地化字符串。
    /// </summary>
    internal static string MsApiCategoryIdErrorMessage {
        get {
            return ResourceManager.GetString("MsApiCategoryIdErrorMessage", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Failed to get languages for translation 的本地化字符串。
    /// </summary>
    internal static string MsApiFailedGetLanguagesMessage {
        get {
            return ResourceManager.GetString("MsApiFailedGetLanguagesMessage", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Failed to translate 的本地化字符串。
    /// </summary>
    internal static string MsApiFailedToTranslateMessage {
        get {
            return ResourceManager.GetString("MsApiFailedToTranslateMessage", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
    /// </summary>
    internal static System.Drawing.Icon my_icon {
        get {
            object obj = ResourceManager.GetObject("my_icon", resourceCulture);
            return ((System.Drawing.Icon)(obj));
        }
    }
    
    /// <summary>
    ///   查找 System.Drawing.Bitmap 类型的本地化资源。
    /// </summary>
    internal static System.Drawing.Bitmap my_image {
        get {
            object obj = ResourceManager.GetObject("my_image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   查找类似 MT Enhanced Trados Plugin - Choose between Google Translate, Baidu Translate or Microsoft Translator 的本地化字符串。
    /// </summary>
    internal static string Plugin_Description {
        get {
            return ResourceManager.GetString("Plugin_Description", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 MT Enhanced Trados Plugin 的本地化字符串。
    /// </summary>
    internal static string Plugin_Name {
        get {
            return ResourceManager.GetString("Plugin_Name", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 MT Enhanced Trados Plugin 的本地化字符串。
    /// </summary>
    internal static string Plugin_NiceName {
        get {
            return ResourceManager.GetString("Plugin_NiceName", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 MT Enhanced Trados Plugin - Choose between Google Translate, Baidu Translate or Microsoft Translator 的本地化字符串。
    /// </summary>
    internal static string Plugin_Tooltip {
        get {
            return ResourceManager.GetString("Plugin_Tooltip", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Credentials for Baidu Translate... 的本地化字符串。
    /// </summary>
    internal static string PromptForCredentialsCaption_Baidu {
        get {
            return ResourceManager.GetString("PromptForCredentialsCaption_Baidu", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Credentials for Google Translate... 的本地化字符串。
    /// </summary>
    internal static string PromptForCredentialsCaption_Google {
        get {
            return ResourceManager.GetString("PromptForCredentialsCaption_Google", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Credentials for Microsoft Translator... 的本地化字符串。
    /// </summary>
    internal static string PromptForCredentialsCaption_Microsoft {
        get {
            return ResourceManager.GetString("PromptForCredentialsCaption_Microsoft", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 [segment already translated...source not re-sent] 的本地化字符串。
    /// </summary>
    internal static string TranslationLookupDraftNotResentMessage {
        get {
            return ResourceManager.GetString("TranslationLookupDraftNotResentMessage", resourceCulture);
        }
    }
    
    /// <summary>
    ///   查找类似 Translation provider URI not supported. 的本地化字符串。
    /// </summary>
    internal static string UriNotSupportedMessage {
        get {
            return ResourceManager.GetString("UriNotSupportedMessage", resourceCulture);
        }
    }
}
